//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoSelect.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoSelect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Move {0} to recycle bin? 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Delete_32px {
            get {
                object obj = ResourceManager.GetObject("Delete_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Mettre {0} dans la corbeille? 的本地化字符串。
        /// </summary>
        internal static string Delete_fr {
            get {
                return ResourceManager.GetString("Delete_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将 {0} 移动到回收站？ 的本地化字符串。
        /// </summary>
        internal static string Delete_zh {
            get {
                return ResourceManager.GetString("Delete_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Open_Folder_32px {
            get {
                object obj = ResourceManager.GetObject("Open_Folder_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Save_32px_1 {
            get {
                object obj = ResourceManager.GetObject("Save_32px_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Images saved to 的本地化字符串。
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images sauvegardés dans  的本地化字符串。
        /// </summary>
        internal static string Saved_fr {
            get {
                return ResourceManager.GetString("Saved_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片已保存到  的本地化字符串。
        /// </summary>
        internal static string Saved_zh {
            get {
                return ResourceManager.GetString("Saved_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;/&quot; : 
        ///  Bookmark selected image
        ///
        ///&quot;↑&quot; / &quot;←&quot; : 
        ///  Select previous image
        ///
        ///&quot;↓&quot; / &quot;→&quot; : 
        ///  Select next image 的本地化字符串。
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;/&quot; : 
        ///  Marquer l&apos;image sélectionnée
        ///
        ///&quot;↑&quot; / &quot;←&quot; : 
        ///  Sélectionner l&apos;image précédente
        ///
        ///&quot;↓&quot; / &quot;→&quot; : 
        ///  Sélectionner l&apos;image suivante 的本地化字符串。
        /// </summary>
        internal static string Shortcuts_fr {
            get {
                return ResourceManager.GetString("Shortcuts_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;/&quot; : 
        ///  为选择的图片添加书签
        ///
        ///&quot;↑&quot; / &quot;←&quot; : 
        ///  选择上一个图片
        ///
        ///&quot;↓&quot; / &quot;→&quot; : 
        ///  选择下一个图片 的本地化字符串。
        /// </summary>
        internal static string Shortcuts_zh {
            get {
                return ResourceManager.GetString("Shortcuts_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcuts 的本地化字符串。
        /// </summary>
        internal static string ShortcutsTitle {
            get {
                return ResourceManager.GetString("ShortcutsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raccourcis 的本地化字符串。
        /// </summary>
        internal static string ShortcutsTitle_fr {
            get {
                return ResourceManager.GetString("ShortcutsTitle_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键 的本地化字符串。
        /// </summary>
        internal static string ShortcutsTitle_zh {
            get {
                return ResourceManager.GetString("ShortcutsTitle_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Star_32px {
            get {
                object obj = ResourceManager.GetObject("Star_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Star_Filled_32px {
            get {
                object obj = ResourceManager.GetObject("Star_Filled_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avertissement 的本地化字符串。
        /// </summary>
        internal static string Warning_fr {
            get {
                return ResourceManager.GetString("Warning_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warning_zh {
            get {
                return ResourceManager.GetString("Warning_zh", resourceCulture);
            }
        }
    }
}
